#!/usr/bin/env bash
_self=$(basename "$0")
usage () {
  cat <<EOF
Use this script to run tshark to capture a log file which can then be processed
using decode.

Parameters:
 1 The Ruida controller IP address.
 2 The capture file name -- not including extension. This saves to $2.log.
 3 Optional parameters. (e.g. "-i <if>")

NOTE: Parameter 3 is often needed on Windows because it typically assumes the
wrong interface. If this is the case use "-i Ethernet".
EOF
exit 1
}

if [ "$#" -ne 3 ]; then
    usage
fi

_ip=$1
if ping -c 1 -W 1 "_ip" &> /dev/null; then
    echo IP address is reachable.
else
    # Be forgiving since a bogus ip or having machine off may be intentional
    # when capturing lost comms behaviors.
    echo Warning: IP address $_ip is not reachable.
    echo Is the machine OFF?
fi

_file=$2

_path=$(dirname $_file)
if [ -e $_path ]; then
    tshark -Y "(ip.addr == $_ip)" $3 -l -T fields \
        -e frame.time_delta -e udp.port -e udp.length -e data.data | tee $_file.log
else
    echo Log file path $_path does not exist.
    usage
fi
