#!/usr/bin/env bash
_self=$(basename "$0")
usage () {
  cat <<EOF
Usage: $_self <file> [<options>]

Use this script to run rpa.py to process a log file previously captured
by the capture script. The log file is processed twice. First to produce a
summarized decode and second to produce a verbose decode.

The verbose decode generates a plot of all moves and steps for each move.

NOTE: This script requires that Python be run in a virtual environment. Be
sure a virtual environment is active before running this script. A
requirements.txt is provided if it is necessary to create a virtual environment.

Parameters:
 1 The capture file name -- not including extension. Processes <file>.log.
   The output is written to <file>.txt and <file>-vrb.txt.
 2 Optional command line arguments for verbose mode. Often this will be used
   to generate a plot of all head movements. e.g.: "--plot-moves --step-moves".
EOF
exit 1
}

if [ "$#" -lt 1 ]; then
    usage
fi

_file=$1
if [ ! -e $_file.log ]; then
    echo ERROR: The log file $_file.log does not exist.
    usage
fi

if [[ -n "$VIRTUAL_ENV" ]]; then
    python rpa.py -o $_file.txt $_file.log
    python rpa.py --verbose --raw $2 -o $_file-vrb.txt $_file.log
else
    echo ERROR: A virtual environment is not active.
    usage
fi
