"""
ScriptGenerator — converts decoded Ruida commands to .rds script format.

This module bridges the decoded output of rpa.py's protocol parser with the
script format used by rpa-script, enabling round-trip verification:
  capture log → rpa.py decode → .rds script → rpa-script → tshark output → rpa.py decode
"""

import os
import re


class ScriptGenerator:
    """Generates .rds script files from decoded parser command data.

    Connects to RdParser via the on_command callback. Receives structured
    command data each time a host→controller command is fully decoded,
    and writes a corresponding script line to the output .rds file.

    Usage:
        gen = ScriptGenerator('output.rds')
        parser.on_command = gen.write_command
        parser.decode(...)
        gen.close()

        # With source tracking:
        gen = ScriptGenerator('output.rds', source_file='capture.log')
    """

    def __init__(self, output_path: str, source_file: str | None = None):
        self._fp = open(output_path, "w", encoding="utf-8")
        self._fp.write("# Generated by rpa.py script generator\n")
        if source_file is not None:
            self._fp.write(f"# Source: {os.path.basename(source_file)}\n")
        self._last_cmd_n = 0
        self._packet_count = 0
        # Buffering for expect= reply values: a command is stored here when
        # first decoded; if a reply arrives (same cmd_n), its value is captured
        # and appended when the buffered line is flushed to file.
        self._pending_line: str | None = None
        self._pending_cmd_n: int | None = None
        self._pending_expect: str | None = None

    def write_command(
        self, *, label, cmd_values, param_list, command, sub_command, decoded, cmd_n
    ):
        """Write a decoded command as a .rds script line.

        Called from RdParser._report_parse for each fully decoded command.
        Buffers the command line until any reply callback arrives (same cmd_n)
        so the reply value can be captured and appended as ``expect=``.
        """
        # --- Reply callback (same cmd_n as the last command) ---
        if cmd_n == self._last_cmd_n:
            if self._pending_expect is None and ":Reply:" in decoded:
                reply_part = decoded.split(":Reply:", 1)[1]
                # Handle unknown values (e.g. from rd_card_id returning Unknown:...)
                if "Unknown" in reply_part or "TBD" in reply_part:
                    self._pending_expect = "?"
                else:
                    self._pending_expect = reply_part
            return

        # --- New command: flush any previously buffered line first ---
        self._flush_pending()

        self._last_cmd_n = cmd_n
        self._pending_cmd_n = cmd_n
        self._pending_expect = None

        line = self._format_line(label, param_list, cmd_values, decoded)
        self._pending_line = line

    def _flush_pending(self):
        """Write the buffered command line to file, appending ``= <expect>`` if a
        reply value was captured from a subsequent callback on the same cmd_n."""
        if self._pending_line is None:
            return
        line = self._pending_line
        if self._pending_expect is not None:
            line += f"  = {self._pending_expect}"
        self._fp.write(line + "\n")
        self._pending_line = None
        self._pending_cmd_n = None

    def on_new_packet(self):
        """Called once per host→controller packet, before any commands in it.

        Fires from RuidaProtocolAnalyzer.decode() when a new host→controller
        packet is read. Writes a blank line and packet-number comment before
        each packet, and a NEW_PACKET marker on every call after the first,
        so the first packet's commands have no preceding NEW_PACKET marker.
        """
        # Flush any pending command line before the packet boundary so the
        # previous packet's commands are fully written with their expect values.
        self._flush_pending()
        self._packet_count += 1
        self._fp.write(f"\n# Packet {self._packet_count}\n")
        if self._packet_count > 1:
            self._fp.write("NEW_PACKET\n")

    def close(self):
        """Close the output file."""
        self._flush_pending()
        if self._fp is not None:
            self._fp.close()
            self._fp = None

    # ------------------------------------------------------------------
    # Line formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_line(label, param_list, cmd_values, decoded) -> str:
        """Format decoded command data as a .rds script line.

        Handles three cases:
        1. No params (str-only command) → just ``label``
        2. Memory command (mt spec) → ``label MEM_MNEMONIC``
        3. Normal params → ``label FMT1 FMT2 ...``
        """
        # Guard: labels must be single tokens (no whitespace) for .rds mnemonic parsing.
        if " " in label.strip() or "\n" in label:
            raise ValueError(
                f"Label {label!r} contains whitespace and cannot be used as a "
                f"single-token .rds mnemonic. Fix the CT table entry."
            )

        # Case 1: no parameter specs — bare command string
        if (
            not param_list
            or not isinstance(param_list, (tuple, list))
            or len(param_list) <= 1
        ):
            return label

        specs = param_list[1:]

        # Case 2: memory command — extract MEM_ mnemonic from decoded string
        if _has_mt_spec(specs):
            mem_name = _extract_mem_mnemonic(decoded)
            if mem_name is not None:
                return f"{label} {mem_name}"
            return label

        # Case 3: normal parameterized command
        params: list[str] = []
        for i, spec in enumerate(specs):
            # Skip action markers (int values like REPLY, SKIP)
            if isinstance(spec, int):
                continue
            # Skip non-tuple specs (dicts for options, etc.)
            if not isinstance(spec, tuple) or len(spec) < 3:
                continue
            if i < len(cmd_values):
                fmt_str = spec[0]
                val = cmd_values[i]

                # Power values need ≥3 decimal places for lossless round-trip through the
                # format→parse→re-encode pipeline.  {:.1f} loses ~39% of uint14 values.
                # (see docs/plans/RuidaDriver-checksum-plan.md)
                if spec[1] == "power":
                    fmt_str = fmt_str.replace("{:.1f}", "{:.3f}")

                # TBD-style debug formats (contain 'TBD' and '{' placeholders)
                # produce complex display text that can't be decoded back.
                # Emit the raw value as a plain integer instead.
                if "TBD" in fmt_str and "{" in fmt_str:
                    params.append(str(val))
                else:
                    try:
                        params.append(fmt_str.format(val))
                    except (ValueError, TypeError):
                        params.append(str(val))

        if params:
            # Sanitize each param: replace whitespace runs with single spaces
            # so embedded newlines/tabs don't break the rds line format.
            clean = []
            for p in params:
                p = " ".join(p.split())
                # Escape '#' characters so inline comment stripping doesn't
                # eat parameter values like 'Color:#FF00FFFF'.
                p = p.replace("#", "\\#")
                clean.append(p)
            return f"{label} {' '.join(clean)}"
        return label

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()


# ------------------------------------------------------------------
# Module-level helpers
# ------------------------------------------------------------------


def _has_mt_spec(specs: tuple) -> bool:
    """Return True if any param spec uses the 'mt' decoder."""
    for s in specs:
        if isinstance(s, tuple) and len(s) >= 2 and s[1] == "mt":
            return True
    return False


def _extract_mem_mnemonic(decoded: str) -> str | None:
    """Extract the MEM_ mnemonic from a decoded string like ``Addr:00:04:MEM_IO_ENABLE``.

    Returns the mnemonic or None if not found.
    """
    m = re.search(r"MEM_[A-Z0-9_]+", decoded)
    return m.group(0).rstrip("_") if m else None
