"""
ScriptGenerator — converts decoded Ruida commands to .rds script format.

This module bridges the decoded output of rpa.py's protocol parser with the
script format used by rpa-script, enabling round-trip verification:
  capture log → rpa.py decode → .rds script → rpa-script → tshark output → rpa.py decode
"""

import re


class ScriptGenerator:
    """Generates .rds script files from decoded parser command data.

    Connects to RdParser via the on_command callback. Receives structured
    command data each time a host→controller command is fully decoded,
    and writes a corresponding script line to the output .rds file.

    Usage:
        gen = ScriptGenerator('output.rds')
        parser.on_command = gen.write_command
        parser.decode(...)
        gen.close()
    """

    def __init__(self, output_path: str):
        self._fp = open(output_path, 'w', encoding='utf-8')
        self._fp.write('# Generated by rpa.py script generator\n')
        self._last_cmd_n = 0

    def write_command(self, *, label, cmd_values, param_list, command,
                      sub_command, decoded, cmd_n):
        """Write a decoded command as a .rds script line.

        Called from RdParser._report_parse for each fully decoded command.
        Skips reply-only updates to the same command (tracked by cmd_n).
        """
        # Guard: skip if this is a reply-only update to the same command.
        if cmd_n == self._last_cmd_n:
            return
        self._last_cmd_n = cmd_n

        line = self._format_line(label, param_list, cmd_values, decoded)
        self._fp.write(line + '\n')

    def close(self):
        """Close the output file."""
        if self._fp is not None:
            self._fp.close()
            self._fp = None

    # ------------------------------------------------------------------
    # Line formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_line(label, param_list, cmd_values, decoded) -> str:
        """Format decoded command data as a .rds script line.

        Handles three cases:
        1. No params (str-only command) → just ``label``
        2. Memory command (mt spec) → ``label MEM_MNEMONIC``
        3. Normal params → ``label FMT1 FMT2 ...``
        """
        # Case 1: no parameter specs — bare command string
        if not param_list or not isinstance(param_list, (tuple, list)) or len(param_list) <= 1:
            return label

        specs = param_list[1:]

        # Case 2: memory command — extract MEM_ mnemonic from decoded string
        if _has_mt_spec(specs):
            mem_name = _extract_mem_mnemonic(decoded)
            if mem_name is not None:
                return f'{label} {mem_name}'
            return label

        # Case 3: normal parameterized command
        params: list[str] = []
        for i, spec in enumerate(specs):
            # Skip action markers (int values like REPLY, SKIP)
            if isinstance(spec, int):
                continue
            # Skip non-tuple specs (dicts for options, etc.)
            if not isinstance(spec, tuple) or len(spec) < 3:
                continue
            if i < len(cmd_values):
                fmt_str = spec[0]
                val = cmd_values[i]
                try:
                    params.append(fmt_str.format(val))
                except (ValueError, TypeError):
                    params.append(str(val))

        if params:
            return f'{label} {" ".join(params)}'
        return label

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()


# ------------------------------------------------------------------
# Module-level helpers
# ------------------------------------------------------------------

def _has_mt_spec(specs: tuple) -> bool:
    """Return True if any param spec uses the 'mt' decoder."""
    for s in specs:
        if isinstance(s, tuple) and len(s) >= 2 and s[1] == 'mt':
            return True
    return False


def _extract_mem_mnemonic(decoded: str) -> str | None:
    """Extract the MEM_ mnemonic from a decoded string like ``Addr:00:04:MEM_IO_ENABLE``.

    Returns the mnemonic or None if not found.
    """
    m = re.search(r'MEM_[A-Z0-9_]+', decoded)
    return m.group(0).rstrip('_') if m else None
