"""
RpaSwizzler — Ruida protocol swizzle/unswizzle with LUT acceleration.

Swizzling is a lightweight XOR obfuscation using a magic byte.
The forward (swizzle) and reverse (unswizzle) operations use the same
four XOR/shift operations (self-inverse) with (b - 1) ↔ (b + 1) swapped.

LUT-based bulk operations precompute all 256 byte mappings for O(1)
lookup, significantly faster than per-byte XOR chains.
"""


class RpaSwizzler:
    """Ruida protocol swizzle/unswizzle with optional LUT acceleration.

    Usage:
        swizzler = RpaSwizzler(magic=0x88)
        swizzler.set_magic(0x88)  # explicitly set and build LUTs

        # Bulk operations (LUT-accelerated)
        swizzled = swizzler.swizzle(bytearray([...]))
        unswizzled = swizzler.unswizzle(bytearray([...]))

        # Single-byte operations (static, no instance needed)
        val = RpaSwizzler.swizzle_byte(0xCC, 0x88)
        val = RpaSwizzler.unswizzle_byte(0xC6, 0x88)
    """

    def __init__(self, magic: int = 0x88):
        self._magic = magic
        self._swizzle_lut: list[int] | None = None
        self._unswizzle_lut: list[int] | None = None

    @property
    def magic(self) -> int:
        """Current magic number."""
        return self._magic

    def set_magic(self, magic: int):
        """Set the magic number and generate swizzle/unswizzle LUTs.

        Builds two 256-entry lookup tables so subsequent bulk swizzle
        and unswizzle operations are simple list-index lookups.
        """
        self._magic = magic
        self._swizzle_lut = [self.swizzle_byte(i, magic) for i in range(256)]
        self._unswizzle_lut = [self.unswizzle_byte(i, magic) for i in range(256)]

    # ------------------------------------------------------------------
    # Static byte-level methods (moved from rpascript/interpreter.py
    # and protocols/ruida/ruida_analyzer.py)
    # ------------------------------------------------------------------

    @staticmethod
    def swizzle_byte(b: int, magic: int) -> int:
        """Forward-swizzle a single byte using *magic*.

        This is the inverse of :meth:`unswizzle_byte`.  The four XOR
        operations are self-inverse; the only difference between forward
        and reverse is ``(b + 1)`` vs ``(b - 1)``.
        """
        b ^= (b >> 7) & 0xFF
        b ^= (b << 7) & 0xFF
        b ^= (b >> 7) & 0xFF
        b ^= magic
        b = (b + 1) & 0xFF
        return b

    @staticmethod
    def unswizzle_byte(b: int, magic: int) -> int:
        """Reverse-unswizzle a single byte using *magic*."""
        b = (b - 1) & 0xFF
        b ^= magic
        b ^= (b >> 7) & 0xFF
        b ^= (b << 7) & 0xFF
        b ^= (b >> 7) & 0xFF
        return b

    # ------------------------------------------------------------------
    # LUT-accelerated bulk methods
    # ------------------------------------------------------------------

    def swizzle(self, data: bytearray) -> bytearray:
        """Swizzle *data* bytearray using the current magic.

        Uses the precomputed swizzle LUT (generated by :meth:`set_magic`).
        If no LUT has been generated yet it is created lazily.
        """
        lut = self._get_swizzle_lut()
        return bytearray(lut[b] for b in data)

    def unswizzle(self, data: bytearray) -> bytearray:
        """Unswizzle *data* bytearray using the current magic.

        Uses the precomputed unswizzle LUT (generated by :meth:`set_magic`).
        If no LUT has been generated yet it is created lazily.
        """
        lut = self._get_unswizzle_lut()
        return bytearray(lut[b] for b in data)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_swizzle_lut(self) -> list[int]:
        if self._swizzle_lut is None:
            self._swizzle_lut = [self.swizzle_byte(i, self._magic) for i in range(256)]
        return self._swizzle_lut

    def _get_unswizzle_lut(self) -> list[int]:
        if self._unswizzle_lut is None:
            self._unswizzle_lut = [self.unswizzle_byte(i, self._magic) for i in range(256)]
        return self._unswizzle_lut
